votingworks/election-manager

client/package.json
client/src/components/QRCode.tsx
client/yarn.lock

I updated `qrcode.react` to export the types so we could use them here. I also rebased on top of zpao/master which mostly just got us this: https://github.com/zpao/qrcode.react/pull/81. We probably won't use it, but it's nice to have.

refactor: use `qrcode.react` types from package

---

client/src/AppRoot.tsx
client/src/components/ElectionManager.tsx
client/src/components/HandMarkedPaperBallot.tsx
client/src/contexts/AppContext.ts
client/src/screens/ExportElectionBallotPackageScreen.tsx

Because there were a lot of side effects to manage, I decided to do a basic state machine kind of thing in `ExportElectionBallotPackageScreen`. This makes it clear what data each state needs and how you get from one state to another.
Additionally, I cleaned up the screen and print ballot elements so that they no longer require IDs and just use refs.

fix: export one copy of each ballot PDF

---

client/src/components/HandMarkedPaperBallot.tsx

Without this, it reads e.g. "Official Ballot forDemocratic 2019 Primary".

fix: ensure there is a space after "for"

---

client/src/screens/BallotScreen.tsx

particularly important cause you can't invoke print any other way with `kiosk-browser`.

print button on ballot page

---

client/src/screens/ExportElectionBallotPackageScreen.tsx
client/src/workflows/ExportElectionBallotPackageWorkflow.test.ts
client/src/workflows/ExportElectionBallotPackageWorkflow.ts

This refactors the state transition code into a separate module, which I'm calling a "workflow", to make it easier to test.
Refs https://github.com/votingworks/vxmail/issues/32

feat: include live and test ballots in a package

---

client/src/components/HandMarkedPaperBallot.tsx

In an effort to move the "default translations" feature out of this branch, I left out a fix.

bug: missing default namespace

---

client/src/data/defaultElection.json
client/src/setupProxy.js

also remove proxy line that I forgot to remove in last PR.
Regarding the date: it would be nice if we could just deal with date data structures, but JavaScript really wants a whole timestamp, so easiest change here is making sure the date field is a fully timezoned ISO-8601 string.
Fixes https://github.com/votingworks/vxmail/issues/85

fix date to be in proper timezone

---

client/src/utils/election.test.ts
client/src/utils/election.ts

Beau pointed out what appeared to be an issue with the file name generation code at https://github.com/votingworks/election-manager/pull/41/files#r450598526. This turned out to not be a problem as it only replaces digits with dashes in the human-readable language names. Still, I was here so I added a test and realized that I no longer needed an optional chain property access before calling `replace`.

test: add test to ensure digits can be in file names

---

client/src/lib/votecounting.ts

As soon as we know it's an overvote or undervote, stop counting it, given that the overvote/undervote computation is happening separately anyways.
Also, fix the expected write-in candidate ID, it's `__write-in`.

don't count a vote the moment it's over or empty

---

client/src/screens/TallyScreen.tsx
client/src/utils/format.test.ts
client/src/utils/format.ts

fix: format tally counts better

---

client/src/AppRoot.tsx
client/src/lib/votecounting.ts
client/src/screens/OvervoteCombinationReportScreen.tsx
client/src/screens/TallyReportScreen.tsx
client/src/screens/TallyScreen.tsx
client/src/utils/CastVoteRecordFiles.ts

- not keeping a map of ballot IDs anymore --> don't want to remove votes silently
- keeping an array of array of CVRs, to not copy large arrays needlessly
- recomputing voteCounts only after a new CVR file is added
- removing kiosk storage for now, will eventually look into compressing
- added a simple "building tabulation report" message since it takes a good while for large CVRs.

More efficient with large CVRs

---

client/src/config/types.ts
client/src/lib/votecounting.ts
client/src/screens/TallyScreen.tsx
client/src/utils/CastVoteRecordFiles.test.ts
client/src/utils/CastVoteRecordFiles.ts

This re-introduces immutability to `CastVoteRecordFiles`, which ensures that we don't accidentally mutate the shared `empty` instance which would pollute any future CVR tallies.

fix: ensure resetting CVRs actually resets things

---

client/src/components/HandMarkedPaperBallot.tsx

Eventually, we may want to embed a ballot ID in the QR code. This adds that capability.
The reason for doing it now is that we need this capability for the Rice usability study. This capability makes sense in the main branch. The next piece of functionality, which will render a particular ballot at a special URL, will only make sense on a temporary branch. That's a next PR to come.

allow ballot ID as a prop in HMPB and use in QR code

---

client/src/components/HandMarkedPaperBallot.tsx

In Ms, it is clearly "Initialing Manager", and we should go with their approach, but realize it may be different from state to state.

make Official Initials text configurable

---

client/src/screens/ExportElectionBallotPackageScreen.tsx
client/src/utils/DownloadableArchive.test.ts
client/src/utils/DownloadableArchive.ts
client/types/kiosk-browser.d.ts

For example, `choctaw-county-general-election-943f5233e4.zip`. Requires https://github.com/votingworks/kiosk-browser/pull/57.

feat: provide a default file name for ballot package

---

client/package.json
client/src/screens/PrintTestDeckScreen.tsx

reducing coverage by a bit cause it's about to go back up and this isn't an actual change in coverage, just an extra line of code.

test deck prints test ballots in non-absentee mode. 

---

client/src/screens/UnconfiguredScreen.tsx

We can eventually do better with an error screen and all, but at least I want this to *not crash* on bad SEMS conversion, which is what this very minimal PR does.

recover from SEMS conversion failure.

---

client/src/components/HandMarkedPaperBallot.tsx

shallow copies are evil. Copy the DOM node properly.

---

client/package.json
client/src/App.test.tsx
client/src/AppRoot.tsx
client/src/components/ElectionManager.tsx
client/src/components/NavigationScreen.tsx
client/src/config/types.ts
client/src/contexts/AppContext.ts
client/src/screens/BallotListScreen.tsx
client/src/screens/BallotScreen.tsx
client/src/screens/DefinitionContestsScreen.tsx
client/src/screens/DefinitionEditorScreen.tsx
client/src/screens/DefinitionScreen.tsx
client/src/screens/ExportElectionBallotPackageScreen.tsx
client/src/screens/OvervoteCombinationReportScreen.tsx
client/src/screens/PrintTestDeckScreen.tsx
client/src/screens/PrintedBallotsReportScreen.tsx
client/src/screens/TallyReportScreen.tsx
client/src/screens/TallyScreen.tsx
client/src/screens/TestDeckScreen.tsx
client/src/screens/UnconfiguredScreen.tsx

Keep track of the exact string that was used to create the hash, and keep them in sync.
This can be deferred if we think the risk is high.

fix: preserve raw configuration and hash

---

client/package.json
client/src/components/HandMarkedPaperBallot.tsx
client/yarn.lock

The QR code encoders/decoders we use are sometimes wrong when the data encoded is not ASCII, so let's just give them ASCII.
Refs votingworks/vxmail#244

fix: base64-encode the QR code data
