votingworks/election-manager

client/src/screens/ExportElectionBallotPackageScreen.tsx
Ha! Forgot that this feature was already added, but commented out.
=> render ballot in export.

client/package.json, client/src/App.test.tsx, client/src/screens/ExportElectionBallotPackageScreen.tsx, client/src/utils/DownloadableArchive.test.ts, client/src/utils/DownloadableArchive.ts, client/test/helpers/fakeFileWriter.ts, client/test/helpers/fakeKiosk.ts, client/tsconfig.json, client/types/compress-commons.d.ts, client/types/kiosk-browser.d.ts, client/types/zip-stream.d.ts, client/yarn.lock
Requires `kiosk-browser` to stream downloads.
=> feat: enable ballot package downloads

client/src/screens/ExportElectionBallotPackageScreen.tsx
=> fix: ensure ballot package contains `election.json`

client/public/ballot/ballot.css, client/src/components/HandMarkedPaperBallot.tsx
Please review this carefully to determine if there is a better way to do this.
=> feat: post-render ballot qr codes

client/src/components/HandMarkedPaperBallot.tsx
This reverts commit a387eef86c282cba2cfd4d7aa5ce3b8b70fbf710.
This fixes the empty election package. @beausmith would love your guidance on how quickly we can merge this. I know it's a bit less convenient for dev, not sure how to solve that.
=> Revert "fix: HMPB renders on page reload."

client/src/AppRoot.tsx, client/src/config/types.ts, client/src/contexts/AppContext.ts, client/src/screens/TallyScreen.tsx, client/src/utils/CastVoteRecordFiles.ts
@eventualbuddha - You'll wanna look at the import and export methods in this PR.
=> Save cvrs in localstorage

client/package.json, client/src/AppRoot.tsx, client/src/screens/ElectionEditDefinitionScreen.tsx, client/src/screens/UnconfiguredScreen.tsx, client/yarn.lock
=> feat: validate election definition against a schema

client/src/App.css, client/src/AppRoot.tsx, client/src/components/Button.tsx, client/src/components/ButtonBar.tsx, client/src/components/FileInputButton.tsx, client/src/components/HorizontalRule.tsx, client/src/components/Modal.tsx, client/src/components/Tally.tsx, client/src/contexts/AppContext.ts, client/src/screens/BallotListScreen.tsx, client/src/screens/TallyReportScreen.tsx, client/src/screens/TallyScreen.tsx, client/src/utils/IntlDateTimeFormats.ts
=> Reports Foundation

client/src/components/PrintButton.tsx, client/src/screens/BallotScreen.tsx, client/src/screens/TallyReportScreen.tsx, client/src/screens/TestDeckScreen.tsx
addresses https://github.com/votingworks/vxmail/issues/84
=> added a PrintButton component that includes a modal.

client/src/components/ContestTally.tsx, client/src/components/ElectionManager.tsx, client/src/config/types.ts, client/src/lib/votecounting.ts, client/src/screens/TallyReportScreen.tsx, client/src/screens/TallyScreen.tsx, client/src/screens/TestDeckScreen.tsx
Please review this PR very carefully. Please test it manually. 
The file `votecounting.ts` could be a lot cleaner with more functional programming… but want automated tests first to ensure that nothing breaks.
=> feat: Scanner Tally Reports.

client/package.json, client/src/components/ContestTally.tsx, client/src/components/HandMarkedPaperBallot.tsx, client/src/config/types.ts, client/src/data/defaultElection.json, client/src/lib/usbstick.test.ts, client/src/lib/votecounting.ts, client/src/screens/TallyReportScreen.tsx, client/src/screens/TallyScreen.tsx, client/src/screens/TestDeckScreen.tsx, client/yarn.lock
Tabulates all yes/no votes correctly with new format.
=> Ballots cast per contest

client/src/screens/TallyReportScreen.tsx
tested in kiosk-browser, works very nicely.
Forgive me for the `alert()`, working to land this quickly, I think it's a reasonable stop-gap for now :)
=> allow saving tabulation report as PDF

client/src/config/types.ts, client/src/lib/__snapshots__/votecounting.test.ts.snap, client/src/lib/votecounting.test.ts, client/src/lib/votecounting.ts
I generated new synthetic CVRs, which caused tallies to change. I manually checked the 3 spot-checks before changing the test values.
=> Pagenum to pagenumber

client/src/config/types.ts, client/src/lib/votecounting.test.ts, client/src/lib/votecounting.ts, client/src/screens/TallyScreen.tsx, client/src/utils/CastVoteRecordFiles.ts
=> fix: do better parsing/validating of CVRs

client/src/components/ContestTally.tsx, client/src/lib/votecounting.ts, client/src/screens/TestDeckScreen.tsx
Viewing Test Deck doesn't crash the app
=> fix: Test Deck has tally meta data.

client/src/components/HandMarkedPaperBallot.tsx
=> feat: No background on ballot instructions.

client/src/AppRoot.tsx
Addresses https://github.com/votingworks/vxmail/issues/100
=> clear official results flag on resetting of CVRs

client/src/components/HandMarkedPaperBallot.tsx
=> Official’s initials box on footer of even pages

client/src/components/HandMarkedPaperBallot.tsx, client/src/components/Text.tsx
To test this, update the description of a `yesno` contest:
```
"description": "Shall the State of Mississippi adopt the following proposed state flag to replace the current state flag? \n\n <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 300 200\"><path fill=\"#fff\" d=\"M0 0h300v200H0z\"/><path d=\"M26.41 87.93H36a7.89 7.89 0 013.52.7 6.54 6.54 0 012.3 1.84 7.17 7.17 0 011.25 2.61 12.15 12.15 0 01.38 3 9.59 9.59 0 01-.63 3.67 6.57 6.57 0 01-1.74 2.52 7.47 7.47 0 01-2.72 1.49 12.43 12.43 0 01-3.53.49h-2.95v10.83h-5.47zm5.47 12.27h2.43a3.6 3.6 0 002.64-1 4.1 4.1 0 001-3.07 4.79 4.79 0 00-.86-3.13 3.58 3.58 0 00-2.93-1h-2.28zM46.17 87.93h5.24v27.13h-5.24zM55.06 100.89v-.5a7 7 0 01.57-3 5.13 5.13 0 011.54-2 6 6 0 012.28-1.06 10.92 10.92 0 012.79-.33 13 13 0 013.78.46 5.13 5.13 0 …
```
=> feat: Support images in YesNo contest description.

client/src/AppRoot.tsx, client/src/components/USBController.tsx, client/src/contexts/AppContext.ts, client/src/lib/usbstick.test.ts, client/src/lib/usbstick.ts, client/test/helpers/fakeKiosk.ts
The trick is to not aggressively remount after ejecting.
=> more intuitive USB drive UX, automount and eject

client/package.json, client/src/App.test.tsx, client/src/components/ElectionManager.tsx, client/src/components/HandMarkedPaperBallot.tsx, client/src/components/TextInput.tsx, client/src/components/Textarea.tsx, client/src/config/types.ts, client/src/routerPaths.ts, client/src/screens/DefinitionContestsScreen.tsx, client/src/screens/DefinitionEditorScreen.tsx, client/src/screens/DefinitionScreen.tsx, client/yarn.lock
=> Election definition editor

client/src/components/Button.tsx, client/src/components/ElectionManager.tsx, client/src/components/HandMarkedPaperBallot.tsx, client/src/components/PrintButton.tsx, client/src/routerPaths.ts, client/src/screens/PrintTestDeckScreen.tsx, client/src/screens/TallyScreen.tsx
I need to add something that waits for all HMPBs to be rendered before showing the print button (cause pagedjs), but it is otherwise working very well.
Now fixed for QR code creation. The only remaining problem is that the content is being created by pagedjs asynchronously, and it would be nice to disable the print button until that's done. I've tried using `afterRendered` in `HandMarkedPaperBallot`, but I'm having trouble figuring out how to update state of the print button without re-rendering all of the HMPBs a second time. Need some React ninja tricks. Help @beausmith you're my only hope.
Still, this is working in every other way.
=> print test deck

client/src/App.test.tsx, client/src/components/Button.tsx, client/src/components/PrintButton.tsx, client/src/screens/BallotScreen.tsx, client/types/kiosk-browser.d.ts
=> Print multiple ballot copies

client/src/components/HandMarkedPaperBallot.tsx
fixes issue where tally report margins are removed
=> Paged js cleanup injected styles

client/src/App.css
With this change the flag SVG images need to be updated such that the `<svg>` tag has a class:
```
<svg class="w-66">
...
</svg>
```
=> Add utility classes for sizing flag width.

client/package.json, client/src/App.test.tsx, client/src/AppRoot.tsx, client/src/__snapshots__/App.test.tsx.snap, client/src/components/HandMarkedPaperBallot.tsx, client/src/lib/votecounting.ts, client/src/screens/BallotScreen.tsx, client/src/screens/ExportElectionBallotPackageScreen.tsx, client/src/screens/PrintTestDeckScreen.tsx, client/src/screens/TallyReportScreen.tsx, client/src/screens/TallyScreen.tsx, client/yarn.lock
This is ready to go other than the one call into `ballot-encoder` that will actually generate the bytes to place inside the QR code.
=> use the binary / compact qr code for hmpb, including election hash

client/src/screens/BallotListScreen.tsx, client/src/screens/BallotScreen.tsx
This addresses the UX workflows that @mattroe shared.
=> feat: BallotList default sort by precinct.

client/src/screens/TallyReportScreen.tsx
=> feat: Informative error message.

client/src/__snapshots__/App.test.tsx.snap, client/src/components/Navigation.tsx
=> feat: Branding in Nav.

client/public/ballot/layout-dual-language.css, client/public/ballot/layout-single-language.css, client/src/__snapshots__/App.test.tsx.snap, client/src/components/HandMarkedPaperBallot.tsx, client/src/components/Prose.tsx
=> feat: Make room for Kanye, et. al.

client/src/lib/votecounting.ts, client/src/screens/TallyReportScreen.tsx, client/src/screens/TallyScreen.tsx
overall or by precinct, to allow for printing zero counts.
=> allow reports to be printed even if vote counts are zero

client/src/lib/ConverterClient.ts, client/src/screens/CombineResultsScreen.tsx, client/src/utils/file.test.ts, client/src/utils/file.ts
This allows loading files from different USB sticks and saving to a third one, too.
=> show error on combining files & copy files in RAM as soon as selected

client/src/screens/TallyScreen.tsx
@eventualbuddha start of PR... I thought I'd do more than your fix, but not finding anything else yet. Feel free to take it and improve it.
=> do not mutate the precinct array

client/.eslintrc.js, client/package.json, client/test/eslint-rules/eslint-plugin-no-array-sort-mutation/index.js, client/test/eslint-rules/eslint-plugin-no-array-sort-mutation/lib/rules/no-array-sort-mutation.js, client/test/eslint-rules/eslint-plugin-no-array-sort-mutation/package.json, client/yarn.lock
=> test: prevent dangerous uses of `Array#sort`

client/src/screens/TallyScreen.tsx
Closes https://github.com/votingworks/vxmail/issues/318.
=> fix(typo): correct "CRV" to "CVR"
